---
# This playbook contains common plays that will be run on all nodes.

- name: Autoremove unused packages
  become: true
  command: apt -y autoremove
  register: autoremove_output
#  changed_when: "'The following packages will be REMOVED' in autoremove_output.stdout"
  changed_when: "'0 upgraded' not in autoremove_output.stdout"
  tags:
    - apt
    - autoremove

- name: Update cache
  become: true
  apt:
    update_cache: yes
  tags:
    - apt
    - updatecache

- name: Update all packages to the latest version
  become: true
  apt:
    upgrade: dist
  tags:
    - apt
    - upgrade

- name: restart machine
  become: true
#  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  shell: nohup bash -c 'sleep 2 && shutdown -r now "Ansible updates triggered"' &
  async: 0
  poll: 0
  ignore_errors: true
  when: reboot.stdout.find('yes') != -1
  tags:
    - restart
    - now

- name: restart wait
  become: false
  local_action: wait_for host={{ ansible_host | default(inventory_hostname,boolean=True) }} search_regex='OpenSSH' port=22 state='started' delay=15 timeout=300
  tags:
    - restart
    - wait
